const APP_VERSION = "v1.0.2 - clipboard copies adjusted to match custom lettering schemes"; 

const regularDrillOptions = [
    "klik", "bip",
    "zap", "zip", "bop", "blip", "bazz", "tik", "tok", "pip", "pop", "ding", "dong",
  ];

const hypeDrillOptions = [
    "jedziesz kurwa!",
    "dawaj kurwa!",
    "szybciej zapierdallaj!",
    "napierdalaj dalej!",
    "szybciej dalej!",
    "dokręcaj te, ręce!",
    "szybcieeeeeej dokręcaaaj!",
    "raz dwaaa trzyyy!",
    "powiedziano raz dwa trzy!",
    "arbajt arbajt!",
    "trzeba ciebie skrócić troszkę!",
    "jazda jazda!",
    "jedziesz ten triceps dalej!",
  ];

const SOLVED_STATE = "UUUUUUUUURRRRRRRRRFFFFFFFFFDDDDDDDDDLLLLLLLLLBBBBBBBBB";
const SOLVED_POSITIONS = [
    [1, 0], [1, 1], [1, 2], [1, 3], [1, 4], [1, 5], [1, 6], [1, 7], [1, 8], // U face
    [2, 9], [2, 10], [2, 11], [2, 12], [2, 13], [2, 14], [2, 15], [2, 16], [2, 17], // R
    [3, 18], [3, 19], [3, 20], [3, 21], [3, 22], [3, 23], [3, 24], [3, 25], [3, 26], // F 
    [4, 27], [4, 28], [4, 29], [4, 30], [4, 31], [4, 32], [4, 33], [4, 34], [4, 35], // D 
    [5, 36], [5, 37], [5, 38], [5, 39], [5, 40], [5, 41], [5, 42], [5, 43], [5, 44], // L 
    [6, 45], [6, 46], [6, 47], [6, 48], [6, 49], [6, 50], [6, 51], [6, 52], [6, 53]  // B 
];
const POSITION_TO_LETTER_MAP = {
    0: 'A', 1: 'A', 2: 'O', 3: 'I', 4: 'UC', 5: 'O', 6: 'I', 7: 'Y', 8: 'Y',
    9: 'M', 10: 'M', 11: 'N', 12: 'P', 13: 'RC', 14: 'N', 15: 'P', 16: 'B', 17: 'B',
    18: 'J', 19: 'U', 20: 'U', 21: 'L', 22: 'FC', 23: 'J', 24: 'L', 25: 'K', 26: 'K',
    27: 'C', 28: 'C', 29: 'D', 30: 'Z', 31: 'DC', 32: 'D', 33: 'Z', 34: 'W', 35: 'W',
    36: 'E', 37: 'E', 38: 'F', 39: 'H', 40: 'LC', 41: 'F', 42: 'H', 43: 'G', 44: 'G',
    45: 'Q', 46: 'Q', 47: 'R', 48: 'T', 49: 'BC', 50: 'R', 51: 'T', 52: 'S', 53: 'S'
};

const DEFAULT_POSITION_TO_LETTER_MAP = {
    0: 'A', 1: 'A', 2: 'O', 3: 'I', 4: 'UC', 5: 'O', 6: 'I', 7: 'Y', 8: 'Y',
    9: 'M', 10: 'M', 11: 'N', 12: 'P', 13: 'RC', 14: 'N', 15: 'P', 16: 'B', 17: 'B',
    18: 'J', 19: 'U', 20: 'U', 21: 'L', 22: 'FC', 23: 'J', 24: 'L', 25: 'K', 26: 'K',
    27: 'C', 28: 'C', 29: 'D', 30: 'Z', 31: 'DC', 32: 'D', 33: 'Z', 34: 'W', 35: 'W',
    36: 'E', 37: 'E', 38: 'F', 39: 'H', 40: 'LC', 41: 'F', 42: 'H', 43: 'G', 44: 'G',
    45: 'Q', 46: 'Q', 47: 'R', 48: 'T', 49: 'BC', 50: 'R', 51: 'T', 52: 'S', 53: 'S'
};

const SPEFFZ_LETTER_MAP = {
    0: 'A', 1: 'A', 2: 'B', 3: 'D', 4: 'UC', 5: 'B', 6: 'D', 7: 'C', 8: 'C',
    9: 'M', 10: 'M', 11: 'N', 12: 'P', 13: 'RC', 14: 'N', 15: 'P', 16: 'O', 17: 'O',
    18: 'I', 19: 'I', 20: 'J', 21: 'L', 22: 'FC', 23: 'J', 24: 'L', 25: 'K', 26: 'K',
    27: 'U', 28: 'U', 29: 'V', 30: 'X', 31: 'DC', 32: 'V', 33: 'X', 34: 'W', 35: 'W',
    36: 'E', 37: 'E', 38: 'F', 39: 'H', 40: 'LC', 41: 'F', 42: 'H', 43: 'G', 44: 'G',
    45: 'Q', 46: 'Q', 47: 'R', 48: 'T', 49: 'BC', 50: 'R', 51: 'T', 52: 'S', 53: 'S'
};

const HANUS_LETTER_MAP = {
    0: 'A', 1: 'A', 2: 'B', 3: 'C', 4: 'UC', 5: 'B', 6: 'C', 7: 'Q', 8: 'Q',
    9: 'M', 10: 'M', 11: 'N', 12: 'P', 13: 'RC', 14: 'N', 15: 'P', 16: 'O', 17: 'O',
    18: 'I', 19: 'I', 20: 'J', 21: 'L', 22: 'FC', 23: 'J', 24: 'L', 25: 'K', 26: 'K',
    27: 'U', 28: 'U', 29: 'W', 30: 'Y', 31: 'DC', 32: 'W', 33: 'Y', 34: 'Z', 35: 'Z',
    36: 'E', 37: 'E', 38: 'F', 39: 'H', 40: 'LC', 41: 'F', 42: 'H', 43: 'G', 44: 'G',
    45: 'D', 46: 'D', 47: 'R', 48: 'T', 49: 'BC', 50: 'R', 51: 'T', 52: 'S', 53: 'S'
};

const CENTER_INDICES = [4, 13, 22, 31, 40, 49];

// Maps for edge and corner piece notation
const EDGE_PIECE_MAP = {
    "A": "UB",
    "O": "UR",
    "I": "UL",
    "E": "LU",
    "F": "LF",
    "G": "LD",
    "H": "LB",
    "J": "FR",
    "K": "FD",
    "L": "FL",
    "M": "RU",
    "N": "RB",
    "B": "RD",
    "P": "RF",
    "Q": "BU",
    "R": "BL",
    "S": "BD",
    "T": "BR",
    "C": "DF",
    "D": "DR",
    "W": "DB",
    "Z": "DL",
};

const CORNER_PIECE_MAP = {
    "A": "UBL",
    "O": "UBR",
    "I": "UFL",
    "E": "LUB",
    "F": "LUF",
    "G": "LDF",
    "H": "LDB",
    "J": "FUL",
    "K": "FDR",
    "L": "FDL",
    "N": "RUB",
    "B": "RDB",
    "P": "RDF",
    "Q": "BUR",
    "R": "BUL",
    "S": "BDL",
    "T": "BDR",
    "C": "DFL",
    "D": "DFR",
    "W": "DBR",
    "Z": "DBL",
};

const LETTER_COLORS = {
    "A": { background: "#EFEFEF", text: "black" }, // White
    "O": { background: "#EFEFEF", text: "black" }, // White
    "I": { background: "#EFEFEF", text: "black" }, // White
    "E": { background: "#FF9900", text: "black" }, // Orange
    "F": { background: "#FF9900", text: "black" }, // Orange
    "G": { background: "#FF9900", text: "black" }, // Orange
    "H": { background: "#FF9900", text: "black" }, // Orange
    "J": { background: "#00FF00", text: "black" }, // Green
    "K": { background: "#00FF00", text: "black" }, // Green
    "L": { background: "#00FF00", text: "black" }, // Green
    "N": { background: "#EA4335", text: "black" }, // Red
    "B": { background: "#EA4335", text: "black" }, // Red
    "P": { background: "#EA4335", text: "black" }, // Red
    "Q": { background: "#4285F4", text: "white" }, // Blue
    "R": { background: "#4285F4", text: "white" }, // Blue
    "S": { background: "#4285F4", text: "white" }, // Blue
    "T": { background: "#4285F4", text: "white" }, // Blue
    "C": { background: "#FFD700", text: "black" }, // Yellow
    "D": { background: "#FFD700", text: "black" }, // Yellow
    "W": { background: "#FFD700", text: "black" }, // Yellow
    "Z": { background: "#FFD700", text: "black" }  // Yellow
};

const single_letter_map = {
    "A": "a",
    "B": "b",
    "C": "c",
    "D": "d",
    "E": "e",
    "F": "f",
    "G": "gie",
    "H": "h",
    "I": "i",
    "J": "jot",
    "K": "k",
    "L": "el",
    "M": "m",
    "N": "n",
    "O": "o",
    "P": "p",
    "Q": "ku",
    "R": "er",
    "S": "es",
    "T": "te",
    "U": "u",
    "W": "wu",
    "Z": "zet"
};

const LETTER_PAIR_TO_WORD = {
    'AA': 'a a',
    'AB': 'a b',
    'AC': 'a c',
    'AD': 'a d',
    'AE': 'a e',
    'AF': 'a f',
    'AG': 'a gie',
    'AH': 'a h',
    'AI': 'a i',
    'AJ': 'a jot',
    'AK': 'a k',
    'AL': 'a el',
    'AM': 'a m',
    'AN': 'a n',
    'AO': 'a o',
    'AP': 'a p',
    'AQ': 'a ku',
    'AR': 'a er',
    'AS': 'a es',
    'AT': 'a te',
    'AW': 'a wu',
    'AZ': 'a zet',
    'BA': 'b a',
    'BB': 'b b',
    'BC': 'b c',
    'BD': 'b d',
    'BE': 'b e',
    'BF': 'b f',
    'BG': 'b gie',
    'BH': 'b h',
    'BI': 'b i',
    'BJ': 'b jot',
    'BK': 'b k',
    'BL': 'b el',
    'BM': 'b m',
    'BN': 'b n',
    'BO': 'b o',
    'BP': 'b p',
    'BQ': 'b ku',
    'BR': 'b er',
    'BS': 'b es',
    'BT': 'b te',
    'BW': 'b wu',
    'BZ': 'b zet',
    'CA': 'c a',
    'CB': 'c b',
    'CC': 'c c',
    'CD': 'c d',
    'CE': 'c e',
    'CF': 'c f',
    'CG': 'c gie',
    'CH': 'c h',
    'CI': 'c i',
    'CJ': 'c jot',
    'CK': 'c k',
    'CL': 'c el',
    'CM': 'c m',
    'CN': 'c n',
    'CO': 'c o',
    'CP': 'c p',
    'CQ': 'c ku',
    'CR': 'c er',
    'CS': 'c es',
    'CT': 'c te',
    'CW': 'c wu',
    'CZ': 'c zet',
    'DA': 'd a',
    'DB': 'd b',
    'DC': 'd c',
    'DD': 'd d',
    'DE': 'd e',
    'DF': 'd f',
    'DG': 'd gie',
    'DH': 'd h',
    'DI': 'd i',
    'DJ': 'd jot',
    'DK': 'd k',
    'DL': 'd el',
    'DM': 'd m',
    'DN': 'd n',
    'DO': 'd o',
    'DP': 'd p',
    'DQ': 'd ku',
    'DR': 'd er',
    'DS': 'd es',
    'DT': 'd te',
    'DW': 'd wu',
    'DZ': 'd zet',
    'EA': 'e a',
    'EB': 'e b',
    'EC': 'e c',
    'ED': 'e d',
    'EE': 'e e',
    'EF': 'e f',
    'EG': 'e gie',
    'EH': 'e h',
    'EI': 'e i',
    'EJ': 'e jot',
    'EK': 'e k',
    'EL': 'e el',
    'EM': 'e m',
    'EN': 'e n',
    'EO': 'e o',
    'EP': 'e p',
    'EQ': 'e ku',
    'ER': 'e er',
    'ES': 'e es',
    'ET': 'e te',
    'EW': 'e wu',
    'EZ': 'e zet',
    'FA': 'f a',
    'FB': 'f b',
    'FC': 'f c',
    'FD': 'f d',
    'FE': 'f e',
    'FF': 'f f',
    'FG': 'f gie',
    'FH': 'f h',
    'FI': 'f i',
    'FJ': 'f jot',
    'FK': 'f k',
    'FL': 'f el',
    'FM': 'f m',
    'FN': 'f n',
    'FO': 'f o',
    'FP': 'f p',
    'FQ': 'f ku',
    'FR': 'f er',
    'FS': 'f es',
    'FT': 'f te',
    'FW': 'f wu',
    'FZ': 'f zet',
    'GA': 'gie a',
    'GB': 'gie b',
    'GC': 'gie c',
    'GD': 'gie d',
    'GE': 'gie e',
    'GF': 'gie f',
    'GG': 'gie gie',
    'GH': 'gie h',
    'GI': 'gie i',
    'GJ': 'gie jot',
    'GK': 'gie k',
    'GL': 'gie el',
    'GM': 'gie m',
    'GN': 'gie n',
    'GO': 'gie o',
    'GP': 'gie p',
    'GQ': 'gie ku',
    'GR': 'gie er',
    'GS': 'gie es',
    'GT': 'gie te',
    'GW': 'gie wu',
    'GZ': 'gie zet',
    'HA': 'h a',
    'HB': 'h b',
    'HC': 'h c',
    'HD': 'h d',
    'HE': 'h e',
    'HF': 'h f',
    'HG': 'h gie',
    'HH': 'h h',
    'HI': 'h i',
    'HJ': 'h jot',
    'HK': 'h k',
    'HL': 'h el',
    'HM': 'h m',
    'HN': 'h n',
    'HO': 'h o',
    'HP': 'h p',
    'HQ': 'h ku',
    'HR': 'h er',
    'HS': 'h es',
    'HT': 'h te',
    'HW': 'h wu',
    'HZ': 'h zet',
    'IA': 'i a',
    'IB': 'i b',
    'IC': 'i c',
    'ID': 'i d',
    'IE': 'i e',
    'IF': 'i f',
    'IG': 'i gie',
    'IH': 'i h',
    'II': 'i i',
    'IJ': 'i jot',
    'IK': 'i k',
    'IL': 'i el',
    'IM': 'i m',
    'IN': 'i n',
    'IO': 'i o',
    'IP': 'i p',
    'IQ': 'i ku',
    'IR': 'i er',
    'IS': 'i es',
    'IT': 'i te',
    'IW': 'i wu',
    'IZ': 'i zet',
    'JA': 'jot a',
    'JB': 'jot b',
    'JC': 'jot c',
    'JD': 'jot d',
    'JE': 'jot e',
    'JF': 'jot f',
    'JG': 'jot gie',
    'JH': 'jot h',
    'JI': 'jot i',
    'JJ': 'jot jot',
    'JK': 'jot k',
    'JL': 'jot el',
    'JM': 'jot m',
    'JN': 'jot n',
    'JO': 'jot o',
    'JP': 'jot p',
    'JQ': 'jot ku',
    'JR': 'jot er',
    'JS': 'jot es',
    'JT': 'jot te',
    'JW': 'jot wu',
    'JZ': 'jot zet',
    'KA': 'k a',
    'KB': 'k b',
    'KC': 'k c',
    'KD': 'k d',
    'KE': 'k e',
    'KF': 'k f',
    'KG': 'k gie',
    'KH': 'k h',
    'KI': 'k i',
    'KJ': 'k jot',
    'KK': 'k k',
    'KL': 'k el',
    'KM': 'k m',
    'KN': 'k n',
    'KO': 'k o',
    'KP': 'k p',
    'KQ': 'k ku',
    'KR': 'k er',
    'KS': 'k es',
    'KT': 'k te',
    'KW': 'k wu',
    'KZ': 'k zet',
    'LA': 'el a',
    'LB': 'el b',
    'LC': 'el c',
    'LD': 'el d',
    'LE': 'el e',
    'LF': 'el f',
    'LG': 'el gie',
    'LH': 'el h',
    'LI': 'el i',
    'LJ': 'el jot',
    'LK': 'el k',
    'LL': 'el el',
    'LM': 'el m',
    'LN': 'el n',
    'LO': 'el o',
    'LP': 'el p',
    'LQ': 'el ku',
    'LR': 'el er',
    'LS': 'el es',
    'LT': 'el te',
    'LW': 'el wu',
    'LZ': 'el zet',
    'MA': 'm a',
    'MB': 'm b',
    'MC': 'm c',
    'MD': 'm d',
    'ME': 'm e',
    'MF': 'm f',
    'MG': 'm gie',
    'MH': 'm h',
    'MI': 'm i',
    'MJ': 'm jot',
    'MK': 'm k',
    'ML': 'm el',
    'MM': 'm m',
    'MN': 'm n',
    'MO': 'm o',
    'MP': 'm p',
    'MQ': 'm ku',
    'MR': 'm er',
    'MS': 'm es',
    'MT': 'm te',
    'MW': 'm wu',
    'MZ': 'm zet',
    'NA': 'n a',
    'NB': 'n b',
    'NC': 'n c',
    'ND': 'n d',
    'NE': 'n e',
    'NF': 'n f',
    'NG': 'n gie',
    'NH': 'n h',
    'NI': 'n i',
    'NJ': 'n jot',
    'NK': 'n k',
    'NL': 'n el',
    'NM': 'n m',
    'NN': 'n n',
    'NO': 'n o',
    'NP': 'n p',
    'NQ': 'n ku',
    'NR': 'n er',
    'NS': 'n es',
    'NT': 'n te',
    'NW': 'n wu',
    'NZ': 'n zet',
    'OA': 'o a',
    'OB': 'o b',
    'OC': 'o c',
    'OD': 'o d',
    'OE': 'o e',
    'OF': 'o f',
    'OG': 'o gie',
    'OH': 'o h',
    'OI': 'o i',
    'OJ': 'o jot',
    'OK': 'o k',
    'OL': 'o el',
    'OM': 'o m',
    'ON': 'o n',
    'OO': 'o o',
    'OP': 'o p',
    'OQ': 'o ku',
    'OR': 'o er',
    'OS': 'o es',
    'OT': 'o te',
    'OW': 'o wu',
    'OZ': 'o zet',
    'PA': 'p a',
    'PB': 'p b',
    'PC': 'p c',
    'PD': 'p d',
    'PE': 'p e',
    'PF': 'p f',
    'PG': 'p gie',
    'PH': 'p h',
    'PI': 'p i',
    'PJ': 'p jot',
    'PK': 'p k',
    'PL': 'p el',
    'PM': 'p m',
    'PN': 'p n',
    'PO': 'p o',
    'PP': 'p p',
    'PQ': 'p ku',
    'PR': 'p er',
    'PS': 'p es',
    'PT': 'p te',
    'PW': 'p wu',
    'PZ': 'p zet',
    'QA': 'ku a',
    'QB': 'ku b',
    'QC': 'ku c',
    'QD': 'ku d',
    'QE': 'ku e',
    'QF': 'ku f',
    'QG': 'ku gie',
    'QH': 'ku h',
    'QI': 'ku i',
    'QJ': 'ku jot',
    'QK': 'ku k',
    'QL': 'ku el',
    'QM': 'ku m',
    'QN': 'ku n',
    'QO': 'ku o',
    'QP': 'ku p',
    'QQ': 'ku ku',
    'QR': 'ku er',
    'QS': 'ku es',
    'QT': 'ku te',
    'QW': 'ku wu',
    'QZ': 'ku zet',
    'RA': 'er a',
    'RB': 'er b',
    'RC': 'er c',
    'RD': 'er d',
    'RE': 'er e',
    'RF': 'er f',
    'RG': 'er gie',
    'RH': 'er h',
    'RI': 'er i',
    'RJ': 'er jot',
    'RK': 'er k',
    'RL': 'er el',
    'RM': 'er m',
    'RN': 'er n',
    'RO': 'er o',
    'RP': 'er p',
    'RQ': 'er ku',
    'RR': 'er er',
    'RS': 'er es',
    'RT': 'er te',
    'RW': 'er wu',
    'RZ': 'er zet',
    'SA': 'es a',
    'SB': 'es b',
    'SC': 'es c',
    'SD': 'es d',
    'SE': 'es e',
    'SF': 'es f',
    'SG': 'es gie',
    'SH': 'es h',
    'SI': 'es i',
    'SJ': 'es jot',
    'SK': 'es k',
    'SL': 'es el',
    'SM': 'es m',
    'SN': 'es n',
    'SO': 'es o',
    'SP': 'es p',
    'SQ': 'es ku',
    'SR': 'es er',
    'SS': 'es es',
    'ST': 'es te',
    'SW': 'es wu',
    'SZ': 'es zet',
    'TA': 'te a',
    'TB': 'te b',
    'TC': 'te c',
    'TD': 'te d',
    'TE': 'te e',
    'TF': 'te f',
    'TG': 'te gie',
    'TH': 'te h',
    'TI': 'te i',
    'TJ': 'te jot',
    'TK': 'te k',
    'TL': 'te el',
    'TM': 'te m',
    'TN': 'te n',
    'TO': 'te o',
    'TP': 'te p',
    'TQ': 'te ku',
    'TR': 'te er',
    'TS': 'te es',
    'TT': 'te te',
    'TW': 'te wu',
    'TZ': 'te zet',
    'WA': 'wu a',
    'WB': 'wu b',
    'WC': 'wu c',
    'WD': 'wu d',
    'WE': 'wu e',
    'WF': 'wu f',
    'WG': 'wu gie',
    'WH': 'wu h',
    'WI': 'wu i',
    'WJ': 'wu jot',
    'WK': 'wu k',
    'WL': 'wu el',
    'WM': 'wu m',
    'WN': 'wu n',
    'WO': 'wu o',
    'WP': 'wu p',
    'WQ': 'wu ku',
    'WR': 'wu er',
    'WS': 'wu es',
    'WT': 'wu te',
    'WW': 'wu wu',
    'WZ': 'wu zet',
    'ZA': 'zet a',
    'ZB': 'zet b',
    'ZC': 'zet c',
    'ZD': 'zet d',
    'ZE': 'zet e',
    'ZF': 'zet f',
    'ZG': 'zet gie',
    'ZH': 'zet h',
    'ZI': 'zet i',
    'ZJ': 'zet jot',
    'ZK': 'zet k',
    'ZL': 'zet el',
    'ZM': 'zet m',
    'ZN': 'zet n',
    'ZO': 'zet o',
    'ZP': 'zet p',
    'ZQ': 'zet ku',
    'ZR': 'zet er',
    'ZS': 'zet es',
    'ZT': 'zet te',
    'ZW': 'zet wu',
    'ZZ': 'zet zet'
}

var keypadLayout = [
    ["b", "S'", "E", "f'", "x", "f", "E'", "S", "b"],
    ["z'", "l'", "L'", "U'", "M'", "U", "R", "r", "z"],
    ["y'", "l", "L", "F'", "M", "F", "R'", "r'", "y"],
    ["d", "B", "u'", "D", "x'", "D'", "u", "B'", "d'"]
]

var defaults = {
    "useVirtual": true,
    "hideTimer": false,
    "includeRecognitionTime": true,
    "showScramble": true,
    "realScrambles": false,
    "randAUF": false,
    "prescramble": false,
    "goInOrder": false,
    "goToNextCase": false,
    "mirrorAllAlgs": false,
    "mirrorAllAlgsAcrossS": false,
    "userDefinedAlgs": "",
    "visualCubeView": "plan",
    "randomizeSMirror": false,
    "randomizeMMirror": false,
};